name: Continuous integration (CI) of mdhelper

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda config --add channels conda-forge
          conda install --file requirements.txt
          conda install flake8 openmm
      - name: Lint with flake8
        run: |
          $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest