on: [push]
jobs:
  build:
    name: continuous-integration-${{ matrix.python-version}}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    timeout-minutes: 60
    steps:      
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python-version}}
      - name: install-dependencies
        run: |
          python3 -m pip install -r requirements_minimal.txt
          conda install openmm
      - name: ruff-lint
        run: |
          python3 -m pip install ruff
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: pytest-test
        run: |
          python3 -m pip install mdanalysistests pytest tidynamics
          pytest