name: continuous-integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          auto-update-conda: true
          channels: conda-forge
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements_minimal.txt
          conda install openmm
      - name: Lint with ruff
        run: |
          python3 -m pip install ruff
          ruff --format=github --target-version=py38 .
        continue-on-error: true
      - name: Test with pytest
        run: |
          python3 -m pip install mdanalysistests pytest tidynamics
          pytest